import 'server-only'

import { normalizeDeviceId } from '@/lib/server/device-id'

/**
 * Prefer the device id in a request header so client reads do not leak the
 * anonymous relationship key into URLs, logs, analytics, or browser history.
 * Device ids are bearer capabilities, so they are accepted only in a header
 * and only in the format generated by FollowApp.
 */
export function requestedDeviceId(req: Request): string | null {
  return normalizeDeviceId(req.headers.get('x-followapp-device-id'))
}
